### ISSUE TITLE
Problem: Missing "staking" module supported transactions

### ISSUE THREAD

**Issue by cdc-Hitesh** [crypto-org-chain/chain-jslib#170]
- [x] MsgCreateValidator
- [x] MsgEditValidator
- [x] MsgDelegate
- [x] MsgBeginRedelegate
- [x] MsgUndelegate

All done as of now.

**Comment by calvinaco** [comment]
Is this still an issue? As all the messages are supported now.

**Comment by cdc-Hitesh** [comment]
> Is this still an issue? As all the messages are supported now.

I will close this one. 
I used it for tracking. Thanks
