### ISSUE TITLE
NFT transaction support

### ISSUE THREAD

**Issue by calvinaco** [crypto-org-chain/chain-jslib#196]
1. To include NFT module protobuf files to the project
2. Support transaction construction for https://github.com/crypto-org-chain/chain-main/blob/master/x/nft/types/tx.pb.go

**Comment by cdc-Hitesh** [comment]
I understand from my research that cosmos-sdk doesn't have these nft types in their repo which we pull while generating the protobuf for our library.

I will pull the types from https://github.com/crypto-org-chain/chain-main/blob/master/x/nft/types`/*.proto`.
Any point to take care of?

**Comment by cdc-Hitesh** [comment]
Types to support:

- [ ] MsgIssueDenom
- [ ] MsgMintNFT
- [ ] MsgEditNFT
- [ ] MsgTransferNFT
- [ ] MsgBurnNFT
