### ISSUE TITLE
address validation

### ISSUE THREAD

**Issue by puffanddmx** [crypto-org-chain/chain-jslib#231]
hi

i have a question!

how can we do the mainnet address type validation with the chain-jslib (return true or false)?
can i know the sample example ?

**Comment by calvinaco** [comment]
Hi @puffanddmx , you can verify a mainnet address using
```
const sdk = require("@crypto-com/chain-jslib");
const isValid = new sdk.utils.AddressValidator({
    network: sdk.CroNetwork.Mainnet,
    address: "test",
    type: sdk.utils.AddressType.USER,
}).isValid();
```

Supported types includes:
User account: `sdk.utils.AddressType.USER`
Validator: `sdk.utils.AddressType.VALIDATOR`

**Comment by puffanddmx** [comment]
thanks! calvinaco

i have one more question.

for the normal sendtransaction , how can you estimate the effective TPS with using sdk?
