### ISSUE TITLE
Problem : Missing governance transaction types support

### ISSUE THREAD

**Issue by eddycpc** [crypto-org-chain/chain-jslib#94]
- [ ] MsgDeposit

- [ ] MsgSubmitProposal

- [x] MsgVote

**Comment by calvinaco** [comment]
More proposal types need to be supported later
https://github.com/crypto-org-chain/chain-jslib/issues/94

**Comment by cdc-Hitesh** [comment]
> * [ ]  MsgDeposit
> * [ ]  MsgSubmitProposal
> * [x]  MsgVote

 [x]  MsgDeposit
 [x]  MsgSubmitProposal
 [x]  MsgVote
