### ISSUE TITLE
Problem : Missing support for MsgSubmitProposal [ gov ]

### ISSUE THREAD

**Issue by eddycpc** [crypto-org-chain/chain-jslib#99]
- [ ] cancel-software-upgrade 
Cancel the current software upgrade proposal

- [x] community-pool-spend    
Submit a community pool spend proposal

- [ ] param-change            
Submit a parameter change proposal

- [ ] software-upgrade        
Submit a software upgrade proposal

Subtask of #94

**Comment by cdc-Hitesh** [comment]
> * [ ]  cancel-software-upgrade
>   Cancel the current software upgrade proposal
> * [x]  community-pool-spend
>   Submit a community pool spend proposal
> * [ ]  param-change
>   Submit a parameter change proposal
> * [ ]  software-upgrade
>   Submit a software upgrade proposal
> 
> Subtask of #94

* [ ]  cancel-software-upgrade
* [x]  community-pool-spend
* [x]  param-change
* [ ]  software-upgrade

**Comment by calvinaco** [comment]
@cdc-Hitesh There should also be a TextProposal which is basically a proposal with arbitrary text content, can you take a look and append to the list of TODOs, thank you!
